import { NextResponse } from "next/server";
import { normalizeText, radarError, readJson } from "../../../../lib/radar-api";
import { getServerSupabaseClient } from "../../../../lib/supabase";

const DEFAULT_ANGLES = [
  { name: "U.S. Market Entry / Regulatory GTM", category: "Fintech / Digital Assets", best_fit_company: "International fintech, RWA, payments, private markets, or trade finance companies considering U.S. expansion.", trigger_signals: ["U.S. launch", "regulatory partnership", "custody", "institutional expansion"], pain_hypothesis: "The company may underestimate the operating complexity of entering the U.S. market across regulatory path, partner map, institutional GTM, custody/compliance dependencies, and execution sequencing.", credibility_points: "Symbridge regulated digital assets ecosystem; SEC/FINRA BD/ATS; NYDFS Trust application; digital commodities/security tokens; DASG advisory.", short_pitch: "I can help assess the U.S. entry path and define a practical 60-90 day execution roadmap.", longer_thesis: "The U.S. market can be attractive but operationally fragmented. A practical entry plan should sequence regulatory posture, partner dependencies, institutional GTM, and execution cadence.", cta: "Would it be useful to compare notes on the U.S. path and pressure-test a practical first 60-90 days?", relevant_resume_template: "Digital Assets / RWA", is_active: true, sort_order: 1 },
  { name: "RWA / Tokenization Strategy & Execution", category: "Digital Assets / RWA", best_fit_company: "Tokenization, digital asset, private markets, fund infrastructure, stablecoin, or on-chain finance companies.", trigger_signals: ["tokenized fund", "RWA product", "stablecoin settlement", "custody integration"], pain_hypothesis: "The company may have product narrative but need sharper institutional positioning, partner execution, compliance-aware GTM, and market segmentation.", credibility_points: "Digital assets strategy; tokenized metals; ATS/BD work; custody/vendor integrations; RWA advisory.", short_pitch: "I can help translate the tokenization thesis into institutional GTM, partner map, and execution roadmap.", longer_thesis: "Tokenization companies often need more than technical proof. They need credible market segmentation, distribution partners, compliance-aware positioning, and operating cadence.", cta: "Open to a short conversation on where the GTM and partnership bottlenecks may be?", relevant_resume_template: "Digital Assets / RWA", is_active: true, sort_order: 2 },
  { name: "Founder’s Office / Strategic Projects", category: "Venture / Startup", best_fit_company: "Seed to Series B companies with founder-led growth, ambiguous execution needs, or new markets.", trigger_signals: ["new funding round", "scaling team", "new market", "founder growth post"], pain_hypothesis: "The company may need senior operating leverage before it is ready for a full-time COO or Chief of Staff.", credibility_points: "Symbridge employee #2/#3; team scaling 2 to 45; fundraising/board materials; startup cofounder/COO; venture build experience.", short_pitch: "I can help turn ambiguous founder priorities into operating cadence and execution across strategy, partnerships, and special projects.", longer_thesis: "Founder-led companies often reach a stage where many strategic projects are important but under-owned. A focused founder’s-office sprint can create traction without adding unnecessary permanent overhead.", cta: "Would a focused 30/60/90 day strategic projects sprint be worth exploring?", relevant_resume_template: "Venture Build/ startup Operator", is_active: true, sort_order: 3 },
  { name: "Partnerships / Corporate Development", category: "Partnerships", best_fit_company: "Fintech, digital asset, infrastructure, marketplace, or venture-backed companies needing ecosystem execution.", trigger_signals: ["partnership", "integration", "ecosystem", "institutional GTM"], pain_hypothesis: "The company may need a structured partner map, prioritized outreach, and execution cadence to convert strategic intent into commercial relationships.", credibility_points: "Partnerships, custody/vendor integrations, capital markets infrastructure, stakeholder management, fintech/regulatory ecosystems.", short_pitch: "I can help turn partnership strategy into a prioritized target map and execution process.", longer_thesis: "Partnership announcements create credibility, but scalable business development requires segmentation, sequencing, stakeholder mapping, and tight follow-through.", cta: "Would it be helpful to pressure-test the partner map and the next set of high-probability targets?", relevant_resume_template: "Strategy & Operations", is_active: true, sort_order: 4 },
  { name: "Trade Finance / Commodity Finance Structuring", category: "Trade Finance", best_fit_company: "Commodity traders, warehouse/collateral platforms, trade finance fintechs, lenders, and RWA collateral companies.", trigger_signals: ["warehouse receipt", "commodity lending", "inventory finance", "collateral"], pain_hypothesis: "The company may need help translating physical trade/collateral workflows into investable, financeable, or digitized structures.", credibility_points: "HTR Consulting; gold/copper financing; receivables; inventory; offtake; commodity finance; warehouse receipt/tokenized collateral research.", short_pitch: "I can help assess financing structure, partner/lender fit, and execution path.", longer_thesis: "Commodity finance opportunities often depend on structuring, collateral control, lender fit, and operational sequencing as much as on market demand.", cta: "Open to a short scoping call on whether the structure is financeable and where execution risk sits?", relevant_resume_template: "Strategy & Operations", is_active: true, sort_order: 5 }
];

function shape(body: any) {
  return {
    name: normalizeText(body.name), category: normalizeText(body.category), best_fit_company: normalizeText(body.best_fit_company),
    trigger_signals: Array.isArray(body.trigger_signals) ? body.trigger_signals.map(String).map((x: string) => x.trim()).filter(Boolean) : [],
    pain_hypothesis: normalizeText(body.pain_hypothesis), credibility_points: normalizeText(body.credibility_points), short_pitch: normalizeText(body.short_pitch), longer_thesis: normalizeText(body.longer_thesis), cta: normalizeText(body.cta), relevant_resume_template: normalizeText(body.relevant_resume_template), is_active: body.is_active !== false, sort_order: Number(body.sort_order) || 0
  };
}

export async function GET() { const supabase = getServerSupabaseClient(); if (!supabase) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); try { const { data, error } = await (supabase as any).from("strategic_angles").select("*").order("sort_order"); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return radarError(error); } }
export async function POST(request: Request) { const supabase = getServerSupabaseClient(); if (!supabase) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); try { const body = await readJson<any>(request); if (body.seed_defaults) { const { data, error } = await (supabase as any).from("strategic_angles").insert(DEFAULT_ANGLES).select("*"); if (error) throw error; return NextResponse.json({ data }, { status: 201 }); } const insert = shape(body); if (!insert.name) return NextResponse.json({ error: "Angle name is required." }, { status: 400 }); const { data, error } = await (supabase as any).from("strategic_angles").insert(insert).select("*").single(); if (error) throw error; return NextResponse.json({ data }, { status: 201 }); } catch (error) { return radarError(error); } }
export async function PATCH(request: Request) { const supabase = getServerSupabaseClient(); if (!supabase) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); try { const body = await readJson<any>(request); if (!body.id) return NextResponse.json({ error: "Angle id is required." }, { status: 400 }); const update = shape(body); delete (update as any).name; if (body.name !== undefined) (update as any).name = normalizeText(body.name); const { data, error } = await (supabase as any).from("strategic_angles").update(update).eq("id", body.id).select("*").single(); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return radarError(error); } }
export async function DELETE(request: Request) { const supabase = getServerSupabaseClient(); if (!supabase) return NextResponse.json({ error: "Supabase is not configured." }, { status: 503 }); try { const body = await readJson<{ id?: string }>(request); if (!body.id) return NextResponse.json({ error: "Angle id is required." }, { status: 400 }); const { error } = await (supabase as any).from("strategic_angles").delete().eq("id", body.id); if (error) throw error; return NextResponse.json({ ok: true }); } catch (error) { return radarError(error); } }
